project_id = "ispnfhpkvzkrfkslwckb"

[functions.search-proxy]
verify_jwt = true

[functions.test-api-keys]
verify_jwt = true

[functions.scraperapi-health]
verify_jwt = false

[functions.username-osint]
verify_jwt = true

[functions.email-breach-search]
verify_jwt = true

[functions.advanced-skiptracer]
verify_jwt = true