// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ispnfhpkvzkrfkslwckb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzcG5maHBrdnprcmZrc2x3Y2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzY5NTIsImV4cCI6MjA3MzYxMjk1Mn0.t-dAkjl-uW6gk646ruHfi1hfx_ueu_YSLZc_MP6Rtfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});